complete -c g -a !  -d 'toggle confirmation'
complete -c g -a a  -d 'add everything'
complete -c g -a bv -d 'branch -vv'
complete -c g -a cc -d 'clean -nfd, confirm, clean -fd'
complete -c g -a c  -d 'commit'
complete -c g -a ca -d 'commit --amend'
complete -c g -a cn -d 'commit --amend --no-edit'
complete -c g -a cb -d 'checkout -b (branch)'
complete -c g -a cl -d 'checkout (remote branch) -b (local branch)'
complete -c g -a cf -d 'attempt to checkout branch by bug name using fzf'
complete -c g -a cs -d 'attempt to checkout branch by bug name'
complete -c g -a cm -d 'commit -m (message)'
complete -c g -a co -d 'checkout (file)'
complete -c g -a d  -d 'diff changes [output_file]'
complete -c g -a dc -d 'diff cached changes [output_file]'
complete -c g -a dh -d 'diff commits [number of commits] [output_file]'
complete -c g -a ds -d 'diff commits [number of commits] - auto names diff [work only]'
complete -c g -a f  -d 'fetch'
complete -c g -a l  -d 'log'
complete -c g -a ll -d 'log graph'
complete -c g -a m  -d 'merge (branch)'
complete -c g -a s  -d 'status'
complete -c g -a rv -d 'remote -vv'
complete -c g -a ri -d 'interactive rebase'
complete -c g -a p  -d 'pause'
complete -c g -a pl -d 'pull --no-edit [branch]'
complete -c g -a pm -d 'pull [branch]'
complete -c g -a ph -d 'push [branch]'
complete -c g -a pf -d 'push --force [branch]'
complete -c g -a su -d 'branch --set-upstream-to=[remote/branch]'
complete -c g -a sc -d 'show conflicting files'
