complete -f -c insync-headless -a accept_all_new_shares
complete -f -c insync-headless -a accept_share
complete -f -c insync-headless -a add_account
complete -f -c insync-headless -a force_sync
complete -f -c insync-headless -a get_account_information
complete -f -c insync-headless -a get_actions_required
complete -f -c insync-headless -a get_domain_link
complete -f -c insync-headless -a get_errors
complete -f -c insync-headless -a get_file_status
complete -f -c insync-headless -a get_link
complete -f -c insync-headless -a get_new_shares
complete -f -c insync-headless -a get_proxy
complete -f -c insync-headless -a get_recent_changes
complete -f -c insync-headless -a get_root_drive_files
complete -f -c insync-headless -a get_status
complete -f -c insync-headless -a get_sync_progress
complete -f -c insync-headless -a manage_ignore_list
complete -f -c insync-headless -a manage_selective_sync
complete -f -c insync-headless -a move_folder
complete -f -c insync-headless -a open_in_gdrive
complete -f -c insync-headless -a pause_syncing
complete -f -c insync-headless -a quit
complete -f -c insync-headless -a reject_all_new_shares
complete -f -c insync-headless -a reject_share
complete -f -c insync-headless -a remove_account
complete -f -c insync-headless -a remove_from_insync
complete -f -c insync-headless -a resume_syncing
complete -f -c insync-headless -a retry_errors
complete -f -c insync-headless -a set_export_option
complete -f -c insync-headless -a set_proxy
complete -f -c insync-headless -a set_selective_sync
complete -f -c insync-headless -a share
complete -f -c insync-headless -a start
