#!/bin/bash

# shellcheck disable=SC1090

# PATH

_maybe_add_path() {
  local target="$1"
  [[ $PATH =~ $target ]] || export PATH="$target":"$PATH"
}

_maybe_add_path ~/.claude/local
_maybe_add_path ~/.local/bin
_maybe_add_path ~/.cargo/bin
_maybe_add_path ~/dotfiles/bin
_maybe_add_path ~/scripts/bin


# ALIASES

alias   ..='cd ..'
alias  ...='cd ../..'
alias ....='cd ../../..'

alias make=gmake


# BEHAVIOR

maybe_source() {
  local target="$1"; [[ -f "$target" ]] && source "$target"
}

maybe_source ~/.fzf.bash
maybe_source ~/.cargo/env

if [ -n "$BASH_VERSION" ]; then
  shopt -s dirspell 2> /dev/null
  shopt -s histappend
  HISTCONTROL=ignoreboth
  HISTSIZE=5000
  HISTFILESIZE=10000
fi


# PRESENTATION

if [ -n "$BASH_VERSION" ] && [[ $- = *i* ]]; then
  # interactive bash
  bind 'set mark-symlinked-directories on'
fi

_terse_pwd() {
  # /home/leaf/google_drive/python -> ~/g/c/python
  printf \
    '%s>' \
    "$( sed -e 's/\([^\/]\)[^\/]*\//\1\//g' <<< "${PWD/$HOME/\~}" )"
}

if [ -n "$BASH_VERSION" ]; then
  export PS1='\u@\h \[\033[38;5;6m\]$( _terse_pwd )\[\e[0m\] '
fi

# colored man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export LSCOLORS=gxfxcxdxBxegedabagacad
