#!/bin/bash

# shellcheck disable=SC1090

# PATH

_maybe_add_path() {
  local target="$1"
  [[ $PATH =~ $target ]] || export PATH="$target":"$PATH"
}

_maybe_add_path ~/.claude/local
_maybe_add_path ~/.local/bin
_maybe_add_path ~/.cargo/bin
_maybe_add_path ~/dotfiles/bin
_maybe_add_path ~/scripts/bin


# ALIASES

alias   ..='cd ..'
alias  ...='cd ../..'
alias ....='cd ../../..'

alias make=gmake


# BEHAVIOR

maybe_source() {
  local target="$1"; [[ -f "$target" ]] && source "$target"
}

maybe_source ~/.fzf.bash
maybe_source ~/.cargo/env

shopt -s dirspell 2> /dev/null

HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=5000
HISTFILESIZE=10000


# PRESENTATION

[[ $- = *i* ]] && {
  # interactive shell
  bind 'set mark-symlinked-directories on'
}

_terse_pwd() {
  # /home/leaf/google_drive/python -> ~/g/c/python
  printf \
    '%s>' \
    "$( sed -e 's/\([^\/]\)[^\/]*\//\1\//g' <<< "${PWD/$HOME/\~}" )"
}

export PS1='\u@\h \[\033[38;5;6m\]$( _terse_pwd )\[\e[0m\] '

# colored man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
