complete -e -c w
complete -f -c w -n __fish_prog_needs_command -a 'add '
complete -f -c w -n '__fish_prog_using_command add' -a 'user '
complete -f -c w -n __fish_prog_needs_command -a 'bookmark '
complete -f -c w -n __fish_prog_needs_command -a 'clean '
complete -f -c w -n '__fish_prog_using_command clean' -a 'files '
complete -f -c w -n __fish_prog_needs_command -a 'do '
complete -f -c w -n '__fish_prog_using_command do' -a 'chromebook '
complete -f -c w -n '__fish_prog_using_command do' -a 'chromebook '
complete -f -c w -n '__fish_prog_using_command chromebook' -a 'swap-search-escape '
complete -f -c w -n '__fish_prog_using_command do' -a 'frequencies '
complete -f -c w -n '__fish_prog_using_command do' -a 'layout '
complete -f -c w -n '__fish_prog_using_command do' -a 'layout '
complete -f -c w -n '__fish_prog_using_command layout' -a 'horizontal '
complete -f -c w -n '__fish_prog_using_command do' -a 'layout '
complete -f -c w -n '__fish_prog_using_command layout' -a 'tiled '
complete -f -c w -n '__fish_prog_using_command do' -a 'layout '
complete -f -c w -n '__fish_prog_using_command layout' -a 'vertical '
complete -f -c w -n '__fish_prog_using_command do' -a 'parse '
complete -f -c w -n '__fish_prog_using_command do' -a 'parse '
complete -f -c w -n '__fish_prog_using_command parse' -a 'json '
complete -f -c w -n '__fish_prog_using_command do' -a 'parse '
complete -f -c w -n '__fish_prog_using_command parse' -a 'xml '
complete -f -c w -n '__fish_prog_using_command do' -a 'pin-to-home '
complete -f -c w -n '__fish_prog_using_command do' -a 'ratio '
complete -f -c w -n __fish_prog_needs_command -a 'install '
complete -f -c w -n '__fish_prog_using_command install' -a 'autojump '
complete -f -c w -n '__fish_prog_using_command install' -a 'docker '
complete -f -c w -n '__fish_prog_using_command install' -a 'dot-files '
complete -f -c w -n '__fish_prog_using_command install' -a 'fish '
complete -f -c w -n '__fish_prog_using_command install' -a 'git '
complete -f -c w -n '__fish_prog_using_command install' -a 'java '
complete -f -c w -n '__fish_prog_using_command install' -a 'lua '
complete -f -c w -n '__fish_prog_using_command install' -a 'shellcheck '
complete -f -c w -n '__fish_prog_using_command install' -a 'vnc '
complete -f -c w -n __fish_prog_needs_command -a 'insync '
complete -f -c w -n '__fish_prog_using_command insync' -a 'errors '
complete -f -c w -n '__fish_prog_using_command insync' -a 'manage-selective-sync '
complete -f -c w -n '__fish_prog_using_command insync' -a 'pause-syncing '
complete -f -c w -n '__fish_prog_using_command insync' -a 'reject-all-new-shares '
complete -f -c w -n '__fish_prog_using_command insync' -a 'resume-syncing '
complete -f -c w -n '__fish_prog_using_command insync' -a 'retry-errors '
complete -f -c w -n '__fish_prog_using_command insync' -a 'start '
complete -f -c w -n '__fish_prog_using_command insync' -a 'status '
complete -f -c w -n '__fish_prog_using_command insync' -a 'sync-progress '
complete -f -c w -n __fish_prog_needs_command -a 'make '
complete -f -c w -n '__fish_prog_using_command make' -a 'file '
complete -f -c w -n '__fish_prog_using_command make' -a 'file '
complete -f -c w -n '__fish_prog_using_command file' -a 'c '
complete -f -c w -n '__fish_prog_using_command make' -a 'file '
complete -f -c w -n '__fish_prog_using_command file' -a 'cpp '
complete -f -c w -n '__fish_prog_using_command make' -a 'file '
complete -f -c w -n '__fish_prog_using_command file' -a 'java '
complete -f -c w -n '__fish_prog_using_command make' -a 'file '
complete -f -c w -n '__fish_prog_using_command file' -a 'python '
complete -f -c w -n '__fish_prog_using_command make' -a 'file '
complete -f -c w -n '__fish_prog_using_command file' -a 'shell '
complete -f -c w -n '__fish_prog_using_command make' -a 'hash '
complete -f -c w -n '__fish_prog_using_command make' -a 'mirror '
complete -f -c w -n '__fish_prog_using_command make' -a 'project '
complete -f -c w -n '__fish_prog_using_command make' -a 'project '
complete -f -c w -n '__fish_prog_using_command project' -a 'c '
complete -f -c w -n '__fish_prog_using_command make' -a 'project '
complete -f -c w -n '__fish_prog_using_command project' -a 'cpp '
complete -f -c w -n '__fish_prog_using_command make' -a 'project '
complete -f -c w -n '__fish_prog_using_command project' -a 'java '
complete -f -c w -n '__fish_prog_using_command make' -a 'project '
complete -f -c w -n '__fish_prog_using_command project' -a 'python '
complete -f -c w -n '__fish_prog_using_command make' -a 'session '
complete -f -c w -n '__fish_prog_using_command make' -a 'tmpfs '
complete -f -c w -n __fish_prog_needs_command -a 'mirror '
complete -f -c w -n '__fish_prog_using_command mirror' -a 'diff '
complete -f -c w -n '__fish_prog_using_command mirror' -a 'pull '
complete -f -c w -n '__fish_prog_using_command mirror' -a 'push '
complete -f -c w -n __fish_prog_needs_command -a 'open '
complete -f -c w -n __fish_prog_needs_command -a 'pkg '
complete -f -c w -n '__fish_prog_using_command pkg' -a 'install '
complete -f -c w -n __fish_prog_needs_command -a 'quick '
complete -f -c w -n '__fish_prog_using_command quick' -a 'c '
complete -f -c w -n '__fish_prog_using_command quick' -a 'python '
complete -f -c w -n '__fish_prog_using_command quick' -a 'shell '
complete -f -c w -n __fish_prog_needs_command -a 'show '
complete -f -c w -n '__fish_prog_using_command show' -a 'disk '
complete -f -c w -n '__fish_prog_using_command show' -a 'history '
complete -f -c w -n '__fish_prog_using_command show' -a 'progress '
complete -f -c w -n '__fish_prog_using_command show' -a 'weather '
complete -f -c w -n __fish_prog_needs_command -a 'start '
complete -f -c w -n '__fish_prog_using_command start' -a 'http-server '
complete -f -c w -n '__fish_prog_using_command start' -a 'sshd '
complete -f -c w -n __fish_prog_needs_command -a 'update '
complete -f -c w -n '__fish_prog_using_command update' -a 'pip '
complete -f -c w -n '__fish_prog_using_command update' -a 'platform '
